version: '3.8'

services:
  # Production build
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '80:80'
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Development server (uncomment for development)
  # react-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: development
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   restart: unless-stopped
